$schema: "./schema_application.yaml"

metadata:
  version: "1.0.0"
  created_date: "2025-07-28"
  description: "TFC Workload Identity Demo Application"

identity:
  name: "tfc-workload-identity-demo"
  contact: "yulei@hashicorp.com"
  environment: "development"
  business_unit: "demo"

authentication:
  aws_auth_role: ""
  pki: ""
  github_repo: ""
  tfc_workspace: "organization:yulei:project:Development:workspace:tfc-workload-identity-demo"

policies:
  identity_policies:
    - "application-identity-token-policies"
    - "super-user"
